// const songData = [
//     { SongName: "Blindings Lights", Artist: "The Weeknd", DateStreamed: "2025-02-10", StreamCount: 5, UserID: "U12345" },
//     { SongName: "Happier Than Ever", Artist: "Billie Eilish", DateStreamed: "2025-02-05", StreamCount: 6, UserID: "U56789" },
//     { SongName: "drivers license", Artist: "Olivia Rodrigo", DateStreamed: "2025-01-30", StreamCount: 8, UserID: "U98765" },
//     { SongName: "Save Your Tears", Artist: "The Weeknd", DateStreamed: "2025-02-12", StreamCount: 3, UserID: "U45678" },
//     { SongName: "Shape of You", Artist: "Ed Sheeran", DateStreamed: "2025-02-14", StreamCount: 10, UserID: "U11223" }
//   ];

//   export default songData;
  const datatable = [
    {
      "SongName": "Blinding Lights",
      "Artist": "The Weeknd",
      "DateStreamed": "2025-02-10",
      "StreamCount": 5,
      "UserID": "U12345",
    },
    {
      "SongName": "Save Your Tears",
      "Artist": "The Weeknd",
      "DateStreamed": "2025-02-04",
      "StreamCount": 6,
      "UserID": "U77221",
    },
    {
      "SongName": "Shape of You",
      "Artist": "Ed Sheeran",
      "DateStreamed": "2025-02-12",
      "StreamCount": 3,
      "UserID": "U67890",
    },
    {
      "SongName": "Castle on the Hill",
      "Artist": "Ed Sheeran",
      "DateStreamed": "2025-02-09",
      "StreamCount": 7,
      "UserID": "U45678",
    },
    {
      "SongName": "Bad Habits",
      "Artist": "Ed Sheeran",
      "DateStreamed": "2025-02-08",
      "StreamCount": 7,
      "UserID": "U54321",
    },
    {
      "SongName": "Industry Baby",
      "Artist": "Lil Nas X",
      "DateStreamed": "2025-02-09",
      "StreamCount": 4,
      "UserID": "U98765",
    },
    {
      "SongName": "Montero",
      "Artist": "Lil Nas X",
      "DateStreamed": "2025-02-01",
      "StreamCount": 10,
      "UserID": "U88888",
    },
    {
      "SongName": "Levitating",
      "Artist": "Dua Lipa",
      "DateStreamed": "2025-02-11",
      "StreamCount": 6,
      "UserID": "U11223",
    },
    {
      "SongName": "Don't Start Now",
      "Artist": "Dua Lipa",
      "DateStreamed": "2025-02-06",
      "StreamCount": 8,
      "UserID": "U33445",
    },
    {
      "SongName": "Heat Waves",
      "Artist": "Glass Animals",
      "DateStreamed": "2025-02-07",
      "StreamCount": 8,
      "UserID": "U55667",
    },
    {
      "SongName": "Tangerine",
      "Artist": "Glass Animals",
      "DateStreamed": "2025-01-30",
      "StreamCount": 5,
      "UserID": "U11234",
    },
    {
      "SongName": "Peaches",
      "Artist": "Justin Bieber",
      "DateStreamed": "2025-02-06",
      "StreamCount": 5,
      "UserID": "U99876",
    },
    {
      "SongName": "Yummy",
      "Artist": "Justin Bieber",
      "DateStreamed": "2025-01-29",
      "StreamCount": 4,
      "UserID": "U12356",
    },
    {
      "SongName": "Stay",
      "Artist": "The Kid LAROI",
      "DateStreamed": "2025-02-05",
      "StreamCount": 9,
      "UserID": "U33221",
    },
    {
      "SongName": "Without You",
      "Artist": "The Kid LAROI",
      "DateStreamed": "2025-02-03",
      "StreamCount": 6,
      "UserID": "U66778",
    },
    {
      "SongName": "Good 4 U",
      "Artist": "Olivia Rodrigo",
      "DateStreamed": "2025-02-03",
      "StreamCount": 4,
      "UserID": "U44566",
    },
    {
      "SongName": "Deja Vu",
      "Artist": "Olivia Rodrigo",
      "DateStreamed": "2025-02-02",
      "StreamCount": 6,
      "UserID": "U11267",
    },
    {
      "SongName": "As It Was",
      "Artist": "Harry Styles",
      "DateStreamed": "2025-02-02",
      "StreamCount": 7,
      "UserID": "U12399",
    },
    {
      "SongName": "Watermelon Sugar",
      "Artist": "Harry Styles",
      "DateStreamed": "2025-01-28",
      "StreamCount": 8,
      "UserID": "U99912",
    },
    {
      "SongName": "Good 4 U",
      "Artist": "Olivia Rodrigo",
      "DateStreamed": "2025-02-03",
      "StreamCount": 4,
      "UserID": "U44566",
    },
    {
      "SongName": "Astronaut In The Ocean",
      "Artist": "Masked Wolf",
      "DateStreamed": "2025-02-12",
      "StreamCount": 6,
      "UserID": "U99811",
    },
    {
      "SongName": "Shivers",
      "Artist": "Ed Sheeran",
      "DateStreamed": "2025-02-05",
      "StreamCount": 8,
      "UserID": "U22334",
    },
    {
      "SongName": "Levitating",
      "Artist": "Dua Lipa",
      "DateStreamed": "2025-02-11",
      "StreamCount": 7,
      "UserID": "U11223",
    },
    {
      "SongName": "Bad Bunny",
      "Artist": "Bad Bunny",
      "DateStreamed": "2025-02-07",
      "StreamCount": 9,
      "UserID": "U87744",
    },
    {
      "SongName": "Dance Monkey",
      "Artist": "Tones and I",
      "DateStreamed": "2025-02-08",
      "StreamCount": 5,
      "UserID": "U33445",
    },
    {
      "SongName": "Levitating",
      "Artist": "Dua Lipa",
      "DateStreamed": "2025-02-04",
      "StreamCount": 6,
      "UserID": "U11223",
    },
    {
      "SongName": "Blinding Lights",
      "Artist": "The Weeknd",
      "DateStreamed": "2025-02-10",
      "StreamCount": 5,
      "UserID": "U12345",
    },
    {
      "SongName": "Montero (Call Me By YourName)",
      "Artist": "Lil Nas X",
      "DateStreamed": "2025-01-30",
      "StreamCount": 10,
      "UserID": "U55555",
    },
    {
      "SongName": "I Gotta Feeling",
      "Artist": "Black Eyed Peas",
      "DateStreamed": "2025-01-29",
      "StreamCount": 7,
      "UserID": "U98712",
    },
    {
      "SongName": "Rolling in the Deep",
      "Artist": "Adele",
      "DateStreamed": "2025-02-01",
      "StreamCount": 8,
      "UserID": "U12232",
    },
    {
      "SongName": "Savage Love",
      "Artist": "Jawsh 685",
      "DateStreamed": "2025-01-28",
      "StreamCount": 4,
      "UserID": "U33445",
    },
    {
      "SongName": "Kiss Me More",
      "Artist": "Doja Cat",
      "DateStreamed": "2025-02-02",
      "StreamCount": 6,
      "UserID": "U98765",
    },
  ];
  export default datatable;